name: develop-stage-promote-2

on:
  schedule:
    - cron: "0/2 * * * *"

jobs:
  stagePromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: origin/stage
      - name: Set output variables
        id: vars
        run: |
          body=$(git log origin/stage...origin/develop)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=pr_title::"Merge `develop` to `stage`"
          echo ::set-output name=pr_body::$body
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: origin/develop
          labels: automerge, automatic
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_body }}
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
