name: develop-stage-promote-2

on:
  schedule:
    - cron: "0/10 * * * *"

jobs:
  stagePromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stage
      - name: Reset promotion branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Set output variables
        id: vars
        run: |
          body=$(git log develop --not stage --pretty=oneline)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=pr_title::"[Auto] Add changes $(date '+on %Y/%m/%d at %H:%M:%S %Z')"
          echo ::set-output name=pr_body::$body
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: develop
          labels: automerge
          title: ${{ steps.vars.outputs.pr_title }}
          body: ${{ steps.vars.outputs.pr_body }}
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
