name: Release Auto-PR
on:
  push:
    branches: ['develop']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "stage"
        pr_title: "Merge `develop` into `release`"
        pr_body: "👑 *An automated PR*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
